### ISSUE TITLE
您好，想咨询一下关于MPandroidChart的问题

### ISSUE THREAD

**Issue by hysheng** [t2314862168/TestParallax#1]
我遇到了个需求，我们项目是做k线图的。有这样个需求，先加载180条数据CandleEntry数据，左滑到最左边时触发分页加载。分页加载过程中，我更换了整个数据源，然后调用了moveViewToX移动到上一次移动的位置，可发现不起作用，反而是直接移动到0的位置上了。分页加载的是历史数据。

**Comment by nuisanceless** [comment]
你好，请问你这个问题解决了吗

**Comment by nuisanceless** [comment]
> 我遇到了个需求，我们项目是做k线图的。有这样个需求，先加载180条数据CandleEntry数据，左滑到最左边时触发分页加载。分页加载过程中，我更换了整个数据源，然后调用了moveViewToX移动到上一次移动的位置，可发现不起作用，反而是直接移动到0的位置上了。分页加载的是历史数据。

你好，请问你这个问题解决了吗
